version: '3.8'

services:
  postgres_dw:
    image: postgres:15-alpine
    container_name: sentinel_dw
    environment:
      POSTGRES_USER: sentinel
      POSTGRES_PASSWORD: sentinel_password
      POSTGRES_DB: sentinel_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata_sentinel:/var/lib/postgresql/data
      # DB 실행 시 스키마 자동 생성을 위한 스크립트 연결
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped

volumes:
  pgdata_sentinel:
