name: 'disease_dbt'
version: '1.0.0'
config-version: 2

profile: 'disease_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  disease_dbt:
    # 모든 모델은 기본적으로 테이블 또는 뷰로 구체화됨 (기본값: view)
    +materialized: view
