disease_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DB_HOST', '127.0.0.1') }}"
      user: "{{ env_var('DB_USER', 'sentinel') }}"
      password: "{{ env_var('DB_PASS', 'sentinel_password') }}"
      port: "{{ env_var('DB_PORT', '5433') | as_number }}"
      dbname: "{{ env_var('DB_NAME', 'sentinel_db') }}"
      schema: analytics
      threads: 1
      keepalives_idle: 0
